#ifndef _CONST_H_
#define _CONST_H_

#define DEBUG

//window
#define DEFAULT_WINDOW_TITLE "Default"
#define DEFAULT_WINDOW_WIDTH 800
#define DEFAULT_WINDOW_HEIGHT 600
#define DEFAULT_WINDOW_FULL_SCREEN false
#define DEFAULT_WINDOW_POSX 0
#define DEFAULT_WINDOW_POSY 0
#define DEFAULT_WINDOW_FRAME_PER_SECOND 60

#define MAX_KEYS 1024
#define MAX_BUTTONS 32

//camera
#define DEFAULT_CAMERA_SENSITIVITY 0.5f
#define DEFAULT_CAMERA_SPEED 5.0f
#define DEFAULT_CAMERA_PFOV 45.0f
#define DEFAULT_CAMERA_PNEAR 0.1f
#define DEFAULT_CAMERA_PFAR 100.0f
#endif